from sqlalchemy import Column, Integer, String, Float, Date
from ..core.database import Base


class SalesData(Base):
    __tablename__ = "sales_data"

    id = Column(Integer, primary_key=True, index=True)
    master_distributor = Column(String, index=True)
    distributor = Column(String, index=True)
    line_of_business = Column(String, index=True)
    supplier = Column(String)
    agency = Column(String)
    category = Column(String, index=True)
    segment = Column(String)
    brand = Column(String, index=True)
    sub_brand = Column(String)
    country = Column(String, index=True)
    city = Column(String, index=True)
    area = Column(String)
    retailer_group = Column(String)
    retailer_sub_group = Column(String)
    channel = Column(String, index=True)
    sub_channel = Column(String)
    salesmen = Column(String)
    order_number = Column(String)
    customer = Column(String)
    customer_account_name = Column(String)
    customer_account_number = Column(String)
    item = Column(String)
    item_description = Column(String)
    promo_item = Column(String)
    foc_nonfoc = Column(String)
    unit_selling_price = Column(Float)
    invoice_number = Column(String)
    invoice_date = Column(Date, index=True)
    year = Column(Integer, index=True)
    month = Column(String)
    invoiced_quantity = Column(Float)
    value = Column(Float)
